config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :contests, only: [:index] do
        resources :performances, only: :index # nested to allow filtering by contest
      end
      resources :performances, only: :create
    end
  end

  resources :categories, only: [:index]

  resources :contests do
    resources :contest_categories, only: [:index, :destroy], shallow: true
    resources :performances, only: [:index, :show], shallow: true
  end

  root 'pages#home'
end

app/models/contest.rb
# == Schema Information
#
# Table name: contests
#
#  id                :integer          not null, primary key
#  season            :integer          not null
#  round             :integer          not null
#  host_id           :integer          not null
#  begins            :date             not null
#  ends              :date             not null
#  certificate_date  :date
#  signup_deadline   :date             not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  timetables_public :boolean          default(FALSE), not null
#

class Contest < ActiveRecord::Base
  include JumuHelper

  belongs_to :host
  has_many :contest_categories, dependent: :destroy
  has_many :categories, through: :contest_categories
  has_many :performances, through: :contest_categories
  has_many :venues, through: :host

  validates :season, presence: true
  validates :round, inclusion: { in: 1..3 }
  validates :host, presence: true
  validates :begins, presence: true
  validates :ends, presence: true
  validates :signup_deadline, presence: true

  validate :require_beginning_before_end
  validate :require_signup_deadline_before_beginning

  def name
    "#{self.host.name}, #{short_name_for_round(self.round)} #{year_for_season(self.season)}"
  end

  private

    def require_beginning_before_end
      unless begins.nil? || ends.nil?
        errors.add(:base, :beginning_not_before_end) if ends < begins
      end
    end

    def require_signup_deadline_before_beginning
      unless begins.nil? || signup_deadline.nil?
        errors.add(:base, :signup_deadline_not_before_beginning) unless signup_deadline < begins
      end
    end
end

app/controllers/api/v1/contests_controller.rb
module API::V1
  class ContestsController < APIController
    def index
      @contests = Contest
        .order('begins DESC')
        .includes(
          { contest_categories: :category },
          :host,
          :venues
        )

      if timetable_filter = params[:timetables_public]
        filter_value = (timetable_filter == "1")
        @contests = @contests.where(timetables_public: filter_value)
      end
    end
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def index
    @contests = policy_scope(Contest)
      .includes(:host)
  end

  def show
    @contest = Contest.find(params[:id])
    authorize(@contest)
  end

  def new
    @contest = Contest.new
    authorize(@contest)

    @rounds = available_rounds
  end

  def create
    @contest = Contest.new(contest_params)
    authorize(@contest)

    if @contest.save
      redirect_to contests_path
    else
      @rounds = available_rounds
      render 'new'
    end
  end

  def edit
    @contest = Contest.find(params[:id])
    authorize(@contest)

    @rounds = available_rounds
  end

  def update
    @contest = Contest.find(params[:id])
    authorize(@contest)

    if @contest.update_attributes(contest_params)
      redirect_to @contest
    else
      @rounds = available_rounds
      render 'edit'
    end
  end

  private

    def contest_params
      params
        .require(:contest)
        .permit(:season, :round, :host_id, :begins, :ends, :signup_deadline, :certificate_date)
    end

    def available_rounds
      [1, 2] # Only allow adding contests for these rounds
    end
end

app/views/contests/_contest_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.input :season, input_html: { value: f.object.season || JUMU_SEASON } %>
<%= f.input :round, collection: @rounds, label_method: lambda { |round| JUMU_ROUND_SHORT_NAMES[round] } %>
<%= f.association :host %>
<%= f.input :begins %>
<%= f.input :ends %>
<%= f.input :signup_deadline %>
<%= f.input :certificate_date %>

app/views/contests/edit.html.erb
<% provide(:title, @contest.name) %>

<%= simple_form_for @contest do |form| %>
  <%= render 'contest_fields', f: form %>
  <%= form.button :submit, class: "button" %>
<% end %>

app/views/contests/index.html.erb
<% provide(:title, "Contests") %>

<% if policy(Contest).create? %>
  <%= link_to "New contest", new_contest_path, class: "button" %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= Contest.human_attribute_name(:name) %></th>
      <th><%= Contest.human_attribute_name(:season) %></th>
      <th><%= Contest.human_attribute_name(:round) %></th>
      <th><%= Contest.human_attribute_name(:host) %></th>
      <th><%= Contest.human_attribute_name(:begins) %></th>
      <th><%= Contest.human_attribute_name(:ends) %></th>
      <th><%= Contest.human_attribute_name(:certificate_date) %></th>
      <th><%= Contest.human_attribute_name(:signup_deadline) %></th>
    </tr>
  </thead>
  <tbody>
    <% @contests.each do |contest| %>
    <tr>
      <td><%= link_to contest.name, contest_path(contest) %></td>
      <td><%= contest.season %></td>
      <td><%= contest.round %></td>
      <td><%= contest.host.name %></td>
      <td><%= contest.begins %></td>
      <td><%= contest.ends %></td>
      <td><%= contest.certificate_date %></td>
      <td><%= contest.signup_deadline %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/contests/new.html.erb
<% provide(:title, "New contest") %>

<%= simple_form_for @contest do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :season, input_html: { value: JUMU_SEASON } %>
  <%= f.input :round, collection: @rounds, label_method: lambda { |round| JUMU_ROUND_SHORT_NAMES[round] } %>
  <%= f.association :host %>
  <%= f.input :begins %>
  <%= f.input :ends %>
  <%= f.input :signup_deadline %>
  <%= f.input :certificate_date %>

  <%= f.button :submit, class: "button" %>
<% end %>

app/views/contests/show.html.erb
<% provide(:title, @contest.name) %>

<%= link_to "Edit contest", edit_contest_path(@contest), class: "button" %>
<%= link_to "Manage contest categories", contest_contest_categories_path(@contest), class: "button" %>

<br />

<%= link_to "Show performances", contest_performances_path(@contest), class: "button" %>