config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :contests, only: [:index] do
        resources :performances, only: :index # nested to allow filtering by contest
      end
      resources :performances, only: :create
    end
  end

  resources :categories, only: [:index]

  resources :contests do
    resources :contest_categories, only: [:index, :destroy], shallow: true
    resources :performances, only: [:index, :show], shallow: true
  end

  root 'pages#home'
end

app/models/contest_category.rb
# == Schema Information
#
# Table name: contest_categories
#
#  id          :integer          not null, primary key
#  contest_id  :integer          not null
#  category_id :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class ContestCategory < ActiveRecord::Base
  belongs_to :contest
  belongs_to :category
  has_many :performances, dependent: :destroy

  validates :contest, presence: true
  validates :category, presence: true
end

app/controllers/contest_categories_controller.rb
class ContestCategoriesController < ApplicationController
  def index
    @contest = Contest.find(params[:contest_id])
    authorize(@contest, :index_contest_categories?)

    @contest_categories = policy_scope(@contest.contest_categories)
      .includes(:category)
  end

  def destroy
    @contest_category = ContestCategory.find(params[:id])
    authorize(@contest_category)

    @contest_category.destroy
    redirect_to contest_contest_categories_path(@contest_category.contest)
  end
end

app/views/contest_categories/index.html.erb
<% provide(:title, "Contest Categories") %>

<table>
  <thead>
    <tr>
      <th><%= ContestCategory.human_attribute_name(:category) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @contest_categories.each do |contest_category| %>
    <tr>
      <td><%= contest_category.category.name %></td>
      <td>
        <%= link_to "Delete", contest_category_path(contest_category),
          method: :delete, class: "button"
        %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>